AWS KMS Integration (#37)
Signed-off-by: Mario Francia <mario@io.builders>
Signed-off-by: Miguel_LZPF <miguel.carpena@io.builders>
Co-authored-by: Mario Francia <mario@io.builders>

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,21 +1,17 @@
-message="$(cat $1)"
-requiredPattern="^(add|remove|cut|fix|update|bump|make|start|stop|refactor|reformat|optimise|document|merge|Add|Remove|Cut|Fix|Update|Bump|Make|Start|Stop|Refactor|Reformat|Optimise|Document|Merge) .*"
-signedOffPattern="Signed-off-by:"
+#!/bin/bash
 
-# Check if the commit message has the required format
-if ! [[ $message =~ $requiredPattern ]]; then
-  echo "❌ Wrong commit message! 😕"
-  echo "The commit message must have this format:"
-  echo "<verb in imperative mood> <what was done>"
-  echo "Allowed verbs in imperative mood: add, cut, fix, bump, make, start, stop, refactor, reformat, optimise, document, merge (in lowercase or capital case)"
-  echo "Example: add login button"
-  exit 1
+# Check if the commit message follows the Conventional Commits format
+echo "$message" | npm run --silent commitlint --edit "$1"
+if [ $? -ne 0 ]; then
+    echo "❌ Invalid commit message format! 😕"
+    exit 1
 fi
 
 # Check if the commit message has a 'Signed-off-by:' line
-if ! [[ $message =~ $signedOffPattern ]]; then
+if ! echo "$message" | grep -q "$signedOffPattern"; then
   echo "❌ Missing 'Signed-off-by:' line! 😕"
   echo "Please add a 'Signed-off-by:' line to your commit message."
+  echo "Message: $message"
   exit 1
 fi
 
